/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2024-04-13 14:17:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.epayment.Bean.ExamFormBean;
import com.epayment.Bean.InstituteBean;
import com.epayment.Bean.StudentBean;
import java.util.List;
import java.util.ArrayList;
import com.epayment.Bean.SubjectBean;

public final class examForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/alljs.jsp", Long.valueOf(1711359392000L));
    _jspx_dependants.put("/allcss.jsp", Long.valueOf(1711359392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.epayment.Bean.StudentBean");
    _jspx_imports_classes.add("com.epayment.Bean.InstituteBean");
    _jspx_imports_classes.add("com.epayment.Bean.ExamFormBean");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.epayment.Bean.SubjectBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");

SubjectBean editSubject =(SubjectBean)request.getAttribute("subB");

      out.write('	');
      out.write('\r');
      out.write('\n');

StudentBean editStudent =(StudentBean)request.getAttribute("sb");

      out.write('\r');
      out.write('\n');

ExamFormBean editExam =(ExamFormBean)request.getAttribute("eb");

      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- META ============================================= -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"\" />\r\n");
      out.write("\t<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DESCRIPTION -->\r\n");
      out.write("\t<meta name=\"description\" content=\"EduChamp : Education HTML Template\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- FAVICONS ICON ============================================= -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"assets/images/msbte logo.png\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/msbte logo.png\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- MOBILE SPECIFIC ============================================= -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- All PLUGINS CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/assets.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/calendar/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- TYPOGRAPHY ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/typography.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SHORTCODES ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/shortcodes/shortcodes.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- STYLESHEETS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/layers.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/settings.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/navigation.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/dashboard.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER END -->\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" <title>Exam Form </title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ttr-opened-sidebar ttr-pinned-sidebar\">\r\n");
      out.write("\t\r\n");
List<SubjectBean>subList=(ArrayList)request.getAttribute("sublist"); 
      out.write('\r');
      out.write('\n');
List<StudentBean>studList=(ArrayList)request.getAttribute("studlist"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- header start -->\r\n");
      out.write("\t<header class=\"ttr-header\">\r\n");
      out.write("\t\t<div class=\"ttr-header-wrapper\">\r\n");
      out.write("\t\t\t<!--sidebar menu toggler start -->\r\n");
      out.write("\t\t\t<div class=\"ttr-toggle-sidebar ttr-material-button\">\r\n");
      out.write("\t\t\t\t<i class=\"ti-close ttr-open-icon\"></i>\r\n");
      out.write("\t\t\t\t<i class=\"ti-menu ttr-close-icon\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--sidebar menu toggler end -->\r\n");
      out.write("\t\t\t<!--logo start -->\r\n");
      out.write("\t\t\t<div class=\"ttr-logo-box\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"Home?action=Dashboard\" class=\"ttr-logo\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"ttr-logo-desktop\" alt=\"\" src=\"assets/images/msbte logo.png\" width=\"160\" height=\"27\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- header end -->\r\n");
      out.write("\t<!-- Left sidebar menu start -->\r\n");
      out.write("\t<div class=\"ttr-sidebar\">\r\n");
      out.write("\t\t<div class=\"ttr-sidebar-wrapper content-scroll\">\r\n");
      out.write("\t\t\t<!-- side menu logo start -->\r\n");
      out.write("\t\t\t<div class=\"ttr-sidebar-logo\">\r\n");
      out.write("\t\t\t\t<a href=\"#\"><img alt=\"\" src=\"assets/images/msbte logo.png\" width=\"122\" height=\"27\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- side menu logo end -->\r\n");
      out.write("\t\t\t<!-- sidebar menu start -->\r\n");
      out.write("\t\t\t<nav class=\"ttr-sidebar-navi\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"studentOption.jsp\" class=\"ttr-material-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-home\"></i></span>\r\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Dashboard</span>\r\n");
      out.write("\t\t                </a>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Student?action=StudentProfile&sid=");
      out.print(session.getAttribute("sid")!=null?session.getAttribute("sid"):"");
      out.write("\" class=\"ttr-material-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-book\"></i></span>\r\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Student Profile</span>\r\n");
      out.write("\t\t                </a>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t            <li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ExamForm?action=examform&sid=");
      out.print(session.getAttribute("sid")!=null?session.getAttribute("sid"):"");
      out.write("\" class=\"ttr-material-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-bookmark-alt\"></i></span>\r\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Exam Form</span>\r\n");
      out.write("\t\t                </a>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t            <li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"ttr-material-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-bookmark-alt\"></i></span>\r\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Hall Ticket</span>\r\n");
      out.write("\t\t                </a>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t            <li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"login?action=studLogout\" class=\"ttr-material-button\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-arrow-left\"></i></span>\r\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Log Out</span>\r\n");
      out.write("\t\t                </a>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t            <li class=\"ttr-seperate\"></li>\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t<!-- sidebar menu end -->\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- sidebar menu end -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Left sidebar menu end -->\r\n");
      out.write("\r\n");
      out.write("\t<!--Main container start -->\r\n");
      out.write("\t<main class=\"ttr-wrapper\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"db-breadcrumb\">\r\n");
      out.write("\t\t\t\t<h4 class=\"breadcrumb-title\">Dashboard</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"db-breadcrumb-list\">\r\n");
      out.write("\t\t\t\t\t<li>Exam Form</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-12 m-b30\">\r\n");
      out.write("\t\t\t<div class=\"widget-box\">\r\n");
      out.write("\t\t\t<div class=\"wc-title\">\r\n");
      out.write("\t\t\t\t<h4>Exam Form</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"widget-inner\">\r\n");
      out.write("\t\t\t<form class=\"edit-profile m-b30\" action=\"ExamForm?action=saveExam\" id=\"myForm\" method=\"post\">\r\n");
      out.write("\t\t\t \t\t\t\t<input type=\"hidden\" name=\"exam_id\" id=\"exam_id\"  /><br/>\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Student photo<i style=\"color: red;\">(Width:800 X Height:809)</i></label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"\" id=\"preview\" style=\"display: none;\" >\r\n");
      out.write("\t\t\t\t\t\t<img src=\"\" style=\"border: 1px solid #ccc;\" name=\"url\" id=\"output\">\r\n");
      out.write("\t\t\t\t\t\t");
if(editStudent!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"fetchimage?type=UserPhoto&image=");
      out.print((editStudent.getStud_photo()!=null)?editStudent.getStud_photo():"");
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"edit_img_url\" value=\"");
      out.print((editStudent!=null)?editStudent.getStud_photo():"");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"url\" id=\"value\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Full Name:</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"fullname\" name=\"fullname\" readonly=\"readonly\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editStudent!=null)?editStudent.getFullname():"");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 col-form-label\">Date Of Birth:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t<input id=\"dob\" name=\"dob\" class=\"form-control\" type=\"date\" readonly=\"readonly\" value=\"");
      out.print((editStudent!=null)?editStudent.getDob():"");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Enrollment No:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"enrollment_no\" name=\"enrollment_no\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editStudent!=null)?editStudent.getEnrollment():"");
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Institude Name:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"institute_name\" name=\"institute_name\" readonly=\"readonly\"class=\"form-control\" type=\"text\" value=\"");
      out.print((editStudent!=null)?editStudent.getInstitute_name():"");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Institute Code:</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t<input  name=\"institute_code\" id=\"institute_code\" readonly=\"readonly\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editStudent!=null)?editStudent.getInstitute_code():"");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 col-form-label\">Select Course Name:</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t     <select id=\"course_name\" name=\"course_name\" class=\"form-control\"  onchange=\"getSubjectDetails();\" required=\"\">\r\n");
      out.write("       \t\t\t <option value=\"\">-- Select Course --</option>\r\n");
      out.write("       \t\t\t <option value=\"Computer\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("Computer")?"selected":"");
      out.write(">CO-Computer Engineering </option>\r\n");
      out.write("       \t\t\t <option value=\"Mechanical\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("Mechanical")?"selected":"");
      out.write(">Mechanical Engineering</option>\r\n");
      out.write("       \t\t\t <option value=\"E&TC\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("E&TC")?"selected":"");
      out.write(">Electronic & Tele.</option>\r\n");
      out.write("       \t\t\t <option value=\"IT\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("IT")?"selected":"");
      out.write(">IT Engineering</option>\r\n");
      out.write("       \t\t\t <option value=\"Civil\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("Civil")?"selected":"");
      out.write(">Civil Engineering</option>\r\n");
      out.write("       \t\t\t <option value=\"Automobile\" ");
      out.print(editSubject!=null && editSubject.getCourse_name().equalsIgnoreCase("Automobile")?"selected":"");
      out.write(">Automobile Engineering</option>\r\n");
      out.write("    \t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\t\t\t\r\n");
      out.write("   \t\t\t <label class=\"col-sm-2 col-form-label\">Select Semester:</label>\r\n");
      out.write("   \t\t\t <div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t<select id=\"semester\" name=\"semester\" class=\"form-control\" onchange=\"getSubjectDetails();\" required=\"\">\r\n");
      out.write("       \t\t\t <option value=\"\">-- Select Semester --</option>\r\n");
      out.write("       \t\t\t <option value=\"sem1\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem1")?"selected":"");
      out.write(">Semester 1</option>\r\n");
      out.write("       \t\t\t <option value=\"sem2\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem2")?"selected":"");
      out.write(">Semester 2</option>\r\n");
      out.write("       \t\t\t <option value=\"sem3\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem3")?"selected":"");
      out.write(">Semester 3</option>\r\n");
      out.write("       \t\t\t <option value=\"sem4\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem4")?"selected":"");
      out.write(">Semester 4</option>\r\n");
      out.write("       \t\t\t <option value=\"sem5\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem5")?"selected":"");
      out.write(">Semester 5</option>\r\n");
      out.write("       \t\t\t <option value=\"sem6\" ");
      out.print(editSubject!=null && editSubject.getSemester().equalsIgnoreCase("sem6")?"selected":"");
      out.write(">Semester 6</option>\r\n");
      out.write("    \t\t\t</select>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-striped mb-0\" id=\"datatable-editable\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <th style=\"width:5%\">Sr.No</th> -->\r\n");
      out.write("\t\t\t\t\t\t<th >Subject Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>TH</th>\r\n");
      out.write("\t\t\t\t\t\t<th>TW</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PR</th>\r\n");
      out.write("\t\t\t\t\t\t<th>OR</th>\r\n");
      out.write("\t\t\t\t\t\t<th>SW</th>\r\n");
      out.write("\t\t\t\t\t\t<th>TM</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PM</th>\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<tbody id=\"subject\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table> <br>\r\n");
      out.write("        \r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Payment Mode :</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"online\" name=\"payment\" value=\"online\" checked=\"checked\"> <label for=\"online\">Online</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"QRcode\" src=\"assets/images/QRScan.jpeg\" width=\"160\" height=\"200\"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"offline\" name=\"payment\" value=\"offline\"> <label for=\"offline\">Offline</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                      <input type=\"hidden\" name=\"status\" id=\"status\" value=\"\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"subject\" id=\"jsonstring\">\r\n");
      out.write("\t\t\t\t\t<button name=\"button\" type=\"submit\" class=\"btn\" id=\"Submit\">Save</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- External JavaScripts -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/magnific-popup/magnific-popup.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/waypoints-min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/counterup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/imagesloaded/imagesloaded.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/masonry.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/filter.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"assets/js/contact.js\"></script>\r\n");
      out.write("<!-- Revolution JavaScripts Files -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.actions.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.kenburn.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.migration.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.navigation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.parallax.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.video.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("\tvar ttrevapi;\r\n");
      out.write("\tvar tpj =jQuery;\r\n");
      out.write("\tif(tpj(\"#rev_slider_486_1\").revolution == undefined){\r\n");
      out.write("\t\trevslider_showDoubleJqueryError(\"#rev_slider_486_1\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tttrevapi = tpj(\"#rev_slider_486_1\").show().revolution({\r\n");
      out.write("\t\t\tsliderType:\"standard\",\r\n");
      out.write("\t\t\tjsFileLocation:\"assets/vendors/revolution/js/\",\r\n");
      out.write("\t\t\tsliderLayout:\"fullwidth\",\r\n");
      out.write("\t\t\tdottedOverlay:\"none\",\r\n");
      out.write("\t\t\tdelay:9000,\r\n");
      out.write("\t\t\tnavigation: {\r\n");
      out.write("\t\t\t\tkeyboardNavigation:\"on\",\r\n");
      out.write("\t\t\t\tkeyboard_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\tmouseScrollNavigation:\"off\",\r\n");
      out.write("\t\t\t\tmouseScrollReverse:\"default\",\r\n");
      out.write("\t\t\t\tonHoverStop:\"on\",\r\n");
      out.write("\t\t\t\ttouch:{\r\n");
      out.write("\t\t\t\t\ttouchenabled:\"on\",\r\n");
      out.write("\t\t\t\t\tswipe_threshold: 75,\r\n");
      out.write("\t\t\t\t\tswipe_min_touches: 1,\r\n");
      out.write("\t\t\t\t\tswipe_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\t\tdrag_block_vertical: false\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t,\r\n");
      out.write("\t\t\t\tarrows: {\r\n");
      out.write("\t\t\t\t\tstyle: \"uranus\",\r\n");
      out.write("\t\t\t\t\tenable: true,\r\n");
      out.write("\t\t\t\t\thide_onmobile: false,\r\n");
      out.write("\t\t\t\t\thide_onleave: false,\r\n");
      out.write("\t\t\t\t\ttmp: '',\r\n");
      out.write("\t\t\t\t\tleft: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"left\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tright: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"right\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tviewPort: {\r\n");
      out.write("\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\toutof:\"pause\",\r\n");
      out.write("\t\t\t\tvisible_area:\"80%\",\r\n");
      out.write("\t\t\t\tpresize:false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tresponsiveLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tvisibilityLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridwidth:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridheight:[768,600,600,600],\r\n");
      out.write("\t\t\tlazyType:\"none\",\r\n");
      out.write("\t\t\tparallax: {\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t\torigo:\"enterpoint\",\r\n");
      out.write("\t\t\t\tspeed:400,\r\n");
      out.write("\t\t\t\tlevels:[5,10,15,20,25,30,35,40,45,50,46,47,48,49,50,55],\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshadow:0,\r\n");
      out.write("\t\t\tspinner:\"off\",\r\n");
      out.write("\t\t\tstopLoop:\"off\",\r\n");
      out.write("\t\t\tstopAfterLoops:-1,\r\n");
      out.write("\t\t\tstopAtSlide:-1,\r\n");
      out.write("\t\t\tshuffle:\"off\",\r\n");
      out.write("\t\t\tautoHeight:\"off\",\r\n");
      out.write("\t\t\thideThumbsOnMobile:\"off\",\r\n");
      out.write("\t\t\thideSliderAtLimit:0,\r\n");
      out.write("\t\t\thideCaptionAtLimit:0,\r\n");
      out.write("\t\t\thideAllCaptionAtLilmit:0,\r\n");
      out.write("\t\t\tdebugMode:false,\r\n");
      out.write("\t\t\tfallbacks: {\r\n");
      out.write("\t\t\t\tsimplifyAll:\"off\",\r\n");
      out.write("\t\t\t\tnextSlideOnWindowFocus:\"off\",\r\n");
      out.write("\t\t\t\tdisableFocusListener:false,\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("     function getSubjectDetails() {\t\r\n");
      out.write("     var course_name=document.getElementById(\"course_name\").value;\r\n");
      out.write("     var semester=document.getElementById(\"semester\").value;\r\n");
      out.write("     $(\"#subject tr\").remove();\r\n");
      out.write("     if(course_name!=='' && semester!==''){\r\n");
      out.write("\t       $.ajax({\r\n");
      out.write("\t          url:\"ExamForm?action=getFormDetails&course_name=\"+course_name+\"&semester=\"+semester,\r\n");
      out.write("\t       \t   success:function(result){\r\n");
      out.write("\t       \t\t$.each(result, function(i, subject) {\r\n");
      out.write("\t       \t\t var sub_choice= result[i].checkbox;\r\n");
      out.write("       \t\t\t $('<tr>').html(\"<td style=font-size:15px;>\" + result[i].subject + \"</td> <td><input type='checkbox' value='TH'></td> <td><input type='checkbox' value='TW'></td> <td><input type='checkbox' value='PR'></td> <td><input type='checkbox' value='OR'></td> <td><input type='checkbox' value='SW'></td> <td><input type='checkbox' value='sub_id'></td> <td><input type='checkbox' value='PM'></td>\").appendTo('#subject');\r\n");
      out.write("\t       \t\t});\r\n");
      out.write("\t       \t   } \r\n");
      out.write("\t          });\r\n");
      out.write("           }\r\n");
      out.write("           \r\n");
      out.write("\t   } \r\n");
      out.write(" </script>\r\n");
      out.write("   \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#Submit\").click(function()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"jsonstring\").value=\"\";\r\n");
      out.write("\tvar jobj=[];\r\n");
      out.write("     $(\"#subject\").find('tr').each(function(i,el){\r\n");
      out.write("\t\tvar $tds=$(this).find('td'),\r\n");
      out.write("\t\tsrno=$tds.eq(0).text(); \r\n");
      out.write("     });\r\n");
      out.write("\t\t\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("/* product=$tds.eq(2).text();\r\n");
      out.write("hsn=$tds.eq(3).text();\r\n");
      out.write("weight=$tds.eq(4).text();\r\n");
      out.write("unit=$tds.eq(5).text();\r\n");
      out.write("mrp=$(this).closest('tr').find(\"td:nth-child(7)\").find(\"#mrp\").val();\r\n");
      out.write("qty=$(this).closest('tr').find(\"td:nth-child(8)\").find(\"#quat\").val();\r\n");
      out.write("rate=$(this).closest('tr').find(\"td:nth-child(9)\").find(\"#rt\").val();\r\n");
      out.write("discountper=$(this).closest('tr').find(\"td:nth-child(10)\").find(\"#disper\").val();\r\n");
      out.write("discount=$(this).closest('tr').find(\"td:nth-child(11)\").find(\"#dis\").val();\r\n");
      out.write("taxable=$tds.eq(11).text();\r\n");
      out.write("cgstper=$tds.eq(12).text();\r\n");
      out.write("cgstrs=$tds.eq(13).text();\r\n");
      out.write("sgstper=$tds.eq(14).text();\r\n");
      out.write("sgstrs=$tds.eq(15).text();\r\n");
      out.write("igstper=$tds.eq(16).text();\r\n");
      out.write("igstrs=$tds.eq(17).text();\r\n");
      out.write("total=$tds.eq(18).text();\r\n");
      out.write("totpur=$(this).closest('tr').find(\"td:nth-child(20)\").find(\"#totpur\").val();\r\n");
      out.write("t_pur=$(this).closest('tr').find(\"td:nth-child(21)\").find(\"#t_pur\").val();\r\n");
      out.write("prod_id=$(this).closest('tr').find(\"td:nth-child(22)\").find(\"#prod_id\").val();\r\n");
      out.write("if(product===null || product===undefined || product==='')\r\n");
      out.write("{alert(\"Please add product details.\");}\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\ts={\r\n");
      out.write("\t\t'product':product,\r\n");
      out.write("\t\t'hsn':hsn,\r\n");
      out.write("\t\t'weight':weight,\r\n");
      out.write("\t\t'unit':unit,\r\n");
      out.write("\t\t'mrp':mrp,\r\n");
      out.write("\t\t'qty':qty,\r\n");
      out.write("\t\t'rate':rate,\r\n");
      out.write("\t\t'discountper':discountper,\r\n");
      out.write("\t\t'discount':discount,\r\n");
      out.write("\t\t'taxable':taxable,\r\n");
      out.write("\t\t'cgst_per':cgstper,\r\n");
      out.write("\t\t'cgst_rs':cgstrs,\r\n");
      out.write("\t\t'sgst_per':sgstper,\r\n");
      out.write("\t\t'sgst_rs':sgstrs,\r\n");
      out.write("\t\t'igst_per':igstper,\r\n");
      out.write("\t\t'igst_rs':igstrs,\r\n");
      out.write("\t\t'total':total,\r\n");
      out.write("\t\t't_pur':t_pur,\r\n");
      out.write("\t\t'totpur':totpur,\r\n");
      out.write("\t\t'totpur':totpur,\r\n");
      out.write("\t\t'prod_id':prod_id,\r\n");
      out.write("\t};\r\n");
      out.write("\tjobj.push(s);\r\n");
      out.write(" } // closing of else\r\n");
      out.write("})// closing of function\r\n");
      out.write("\r\n");
      out.write("var jstring=JSON.stringify(jobj);\r\n");
      out.write("var saleid=document.getElementById(\"sale_id\").value;\r\n");
      out.write("var invoiceid=document.getElementById(\"invoiceid\").value;\r\n");
      out.write("\r\n");
      out.write("if(jstring==='[]'){\r\n");
      out.write("alert(\"Please add Store Product.\");\r\n");
      out.write("}\r\n");
      out.write("else{\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"jsonstring\").value=jstring;\r\n");
      out.write("var customer_name=document.getElementById(\"customer_name\").value;\r\n");
      out.write("var consignee_name=document.getElementById(\"consignee_name\").value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(customer_name===''){\r\n");
      out.write("alert(\"Please Fill Customer Name\");\r\n");
      out.write("document.getElementById(\"customer_name\").focus();\r\n");
      out.write("}\r\n");
      out.write("/* else if(consignee_name===''){\r\n");
      out.write("alert(\"Please Fill Shipped Name\");\r\n");
      out.write("document.getElementById(\"consignee_name\").focus();\r\n");
      out.write("} */\r\n");
      out.write("/* else\r\n");
      out.write("{\r\n");
      out.write("document.getElementById(\"myForm\").submit();\r\n");
      out.write("setTimeout(function()\r\n");
      out.write("{\r\n");
      out.write("\t   window.location.reload(1);\r\n");
      out.write("}, 3000);\r\n");
      out.write("}  */\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
