/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2024-04-14 18:03:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/alljs.jsp", Long.valueOf(1711359392000L));
    _jspx_dependants.put("/allcss.jsp", Long.valueOf(1713035840294L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1713035871727L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- META ============================================= -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"\" />\r\n");
      out.write("\t<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DESCRIPTION -->\r\n");
      out.write("\t<meta name=\"description\" content=\"EduChamp : Education HTML Template\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- FAVICONS ICON ============================================= -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"assets/images/msbte logo.png\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/msbte logo.png\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- MOBILE SPECIFIC ============================================= -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- All PLUGINS CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/assets.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/calendar/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- TYPOGRAPHY ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/typography.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SHORTCODES ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/shortcodes/shortcodes.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- STYLESHEETS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/layers.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/settings.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/navigation.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/dashboard.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER END -->\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

 response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"bg\">\n");
      out.write("<div class=\"page-wraper\">\n");
      out.write("\t<!-- Header Top ==== -->\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"bg\">\r\n");

 response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

      out.write("\r\n");
      out.write("\t<!-- Header Top ==== -->\r\n");
      out.write("    <header class=\"header rs-nav\">\r\n");
      out.write("\t\t<div class=\"sticky-header navbar-expand-lg\">\r\n");
      out.write("             <a href=\"Home?action=Dashboard\"><img src=\"assets/images/MaharashtraSBTEHeader.jpg\" alt=\"logo\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("     <!-- Header Top END ==== -->  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \n");
      out.write("    <!-- Header Top END ==== -->\n");
      out.write("    <!-- Content -->\n");
      out.write("    <div class=\"page-content bg-white\">\n");
      out.write("        <!-- Main Slider -->\n");
      out.write("        <div class=\"rev-slider\">\n");
      out.write("\t\t\t<div id=\"rev_slider_486_1_wrapper\" class=\"rev_slider_wrapper fullwidthbanner-container\" data-alias=\"news-gallery36\" data-source=\"gallery\" style=\"margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:0px;\">\n");
      out.write("\t\t\t\t<!-- START REVOLUTION SLIDER 5.3.0.2 fullwidth mode -->\n");
      out.write("\t\t\t\t<div id=\"rev_slider_486_1\" class=\"rev_slider fullwidthabanner\" style=\"display:none;\" data-version=\"5.3.0.2\">\n");
      out.write("\t\t\t\t\t<ul>\t<!-- SLIDE  -->\n");
      out.write("\t\t\t\t\t\t<li data-index=\"rs-100\" \n");
      out.write("\t\t\t\t\t\tdata-transition=\"parallaxvertical\" \n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-hideafterloop=\"0\" \n");
      out.write("\t\t\t\t\t\tdata-hideslideonmobile=\"off\" \n");
      out.write("\t\t\t\t\t\tdata-easein=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-easeout=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-masterspeed=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-thumb=\"error-404.html\" \n");
      out.write("\t\t\t\t\t\tdata-rotate=\"0\" \n");
      out.write("\t\t\t\t\t\tdata-fstransition=\"fade\" \n");
      out.write("\t\t\t\t\t\tdata-fsmasterspeed=\"1500\" \n");
      out.write("\t\t\t\t\t\tdata-fsslotamount=\"7\" \n");
      out.write("\t\t\t\t\t\tdata-saveperformance=\"off\" \n");
      out.write("\t\t\t\t\t\tdata-title=\"A STUDY ON HAPPINESS\" \n");
      out.write("\t\t\t\t\t\tdata-param1=\"\" data-param2=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param3=\"\" data-param4=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param5=\"\" data-param6=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param7=\"\" data-param8=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param9=\"\" data-param10=\"\" \n");
      out.write("\t\t\t\t\t\tdata-description=\"Science says that Women are generally happier\">\n");
      out.write("\t\t\t\t\t\t\t<!-- MAIN IMAGE -->\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/images/background/MSBTE  bg.jpg\" alt=\"\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgposition=\"center center\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgfit=\"cover\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgparallax=\"10\" \n");
      out.write("\t\t\t\t\t\t\t\tclass=\"rev-slidebg\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-no-retina />\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- LAYER NR. 1 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption tp-shape tp-shapewrapper \" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-100-layer-1\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" data-hoffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['middle','middle','middle','middle']\" data-voffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"nowrap\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"shape\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-basealign=\"slide\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"off\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive=\"off\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"opacity:0;\",\"speed\":1,\"to\":\"o:1;\",\"delay\":0,\"ease\":\"Power4.easeOut\"},{\"delay\":\"wait\",\"speed\":1,\"to\":\"opacity:0;\",\"ease\":\"Power4.easeOut\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['left','left','left','left']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"z-index: 5;background-color:rgba(2, 0, 11, 0.80);border-color:rgba(0, 0, 0, 0);border-width:0px;\"> </div>\t\n");
      out.write("\t\t\t\t\t\t\t<!-- LAYER NR. 2 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption Newspaper-Title   tp-resizeme\" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-100-layer-2\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-hoffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['top','top','top','top']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-voffset=\"['250','250','250','240']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-fontsize=\"['50','50','50','30']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-lineheight=\"['55','55','55','35']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"normal\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"text\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"on\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;\",\"mask\":\"x:0px;y:0px;s:inherit;e:inherit;\",\"speed\":1500,\"to\":\"o:1;\",\"delay\":1000,\"ease\":\"Power3.easeInOut\"},{\"delay\":\"wait\",\"speed\":1000,\"to\":\"auto:auto;\",\"mask\":\"x:0;y:0;s:inherit;e:inherit;\",\"ease\":\"Power3.easeInOut\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['center','center','center','center']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[10,10,10,10]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"z-index: 6; font-family:rubik; font-weight:700; text-align:center; white-space: normal;\">\n");
      out.write("\t\t\t\t\t\t\t\t\tWelcome To MSBTE\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li data-index=\"rs-200\" \n");
      out.write("\t\t\t\t\t\tdata-transition=\"parallaxvertical\" \n");
      out.write("\t\t\t\t\t\tdata-slotamount=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-hideafterloop=\"0\" \n");
      out.write("\t\t\t\t\t\tdata-hideslideonmobile=\"off\" \n");
      out.write("\t\t\t\t\t\tdata-easein=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-easeout=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-masterspeed=\"default\" \n");
      out.write("\t\t\t\t\t\tdata-thumb=\"assets/images/background/MSBTE  bg.jpg\" \n");
      out.write("\t\t\t\t\t\tdata-rotate=\"0\" \n");
      out.write("\t\t\t\t\t\tdata-fstransition=\"fade\" \n");
      out.write("\t\t\t\t\t\tdata-fsmasterspeed=\"1500\" \n");
      out.write("\t\t\t\t\t\tdata-fsslotamount=\"7\" \n");
      out.write("\t\t\t\t\t\tdata-saveperformance=\"off\" \n");
      out.write("\t\t\t\t\t\tdata-title=\"A STUDY ON HAPPINESS\" \n");
      out.write("\t\t\t\t\t\tdata-param1=\"\" data-param2=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param3=\"\" data-param4=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param5=\"\" data-param6=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param7=\"\" data-param8=\"\" \n");
      out.write("\t\t\t\t\t\tdata-param9=\"\" data-param10=\"\" \n");
      out.write("\t\t\t\t\t\tdata-description=\"Science says that Women are generally happier\">\n");
      out.write("\t\t\t\t\t\t\t<!-- <!-- MAIN IMAGE -->\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/images/background/MSBTE  bg.jpg\" alt=\"\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgposition=\"center center\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgfit=\"cover\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgrepeat=\"no-repeat\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-bgparallax=\"10\" \n");
      out.write("\t\t\t\t\t\t\t\tclass=\"rev-slidebg\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-no-retina /> -->\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- LAYER NR. 1 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption tp-shape tp-shapewrapper \" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-200-layer-1\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" data-hoffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['middle','middle','middle','middle']\" data-voffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"nowrap\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"shape\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-basealign=\"slide\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"off\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive=\"off\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"opacity:0;\",\"speed\":1,\"to\":\"o:1;\",\"delay\":0,\"ease\":\"Power4.easeOut\"},{\"delay\":\"wait\",\"speed\":1000,\"to\":\"opacity:1;\",\"ease\":\"Power4.easeOut\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['left','left','left','left']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"z-index: 5;background-color:rgba(2, 0, 11, 0.80);border-color:rgba(0, 0, 0, 0);border-width:0px;\"> \n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- LAYER NR. 2 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption Newspaper-Title   tp-resizeme\" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-200-layer-2\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-hoffset=\"['0','0','0','0']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['top','top','top','top']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-voffset=\"['250','250','250','240']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-fontsize=\"['50','50','50','30']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-lineheight=\"['55','55','55','35']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"full\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"normal\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"text\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"on\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;\",\"mask\":\"x:0px;y:0px;s:inherit;e:inherit;\",\"speed\":1500,\"to\":\"o:1;\",\"delay\":1000,\"ease\":\"Power3.easeInOut\"},{\"delay\":\"wait\",\"speed\":1000,\"to\":\"auto:auto;\",\"mask\":\"x:0;y:0;s:inherit;e:inherit;\",\"ease\":\"Power3.easeInOut\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['center','center','center','center']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[10,10,10,10]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[0,0,0,0]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"z-index: 6; font-family:rubik; font-weight:700; text-align:center; white-space: normal;text-transform:uppercase;\">\n");
      out.write("\t\t\t\t\t\t\t\t\tWelcome To MSBTE\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- LAYER NR. 4 -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption Newspaper-Button rev-btn \" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-200-layer-5\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-hoffset=\"['90','80','75','90']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['top','top','top','top']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-voffset=\"['400','400','400','420']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"nowrap\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"button\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"on\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive=\"off\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;\",\"mask\":\"x:0px;y:0px;\",\"speed\":1500,\"to\":\"o:1;\",\"delay\":1000,\"ease\":\"Power3.easeInOut\"},{\"delay\":\"wait\",\"speed\":1000,\"to\":\"auto:auto;\",\"mask\":\"x:0;y:0;\",\"ease\":\"Power3.easeInOut\"},{\"frame\":\"hover\",\"speed\":\"300\",\"ease\":\"Power1.easeInOut\",\"to\":\"o:1;rX:0;rY:0;rZ:0;z:0;\",\"style\":\"c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:1px 1px 1px 1px;\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['center','center','center','center']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[12,12,12,12]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[30,35,35,15]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[12,12,12,12]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[30,35,35,15]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"\"> </div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tp-caption Newspaper-Button rev-btn\" \n");
      out.write("\t\t\t\t\t\t\t\tid=\"slide-200-layer-6\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-x=\"['center','center','center','center']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-hoffset=\"['-90','-80','-75','-90']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-y=\"['top','top','top','top']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-voffset=\"['400','400','400','420']\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-width=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-height=\"none\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-whitespace=\"nowrap\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-type=\"button\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive_offset=\"on\" \n");
      out.write("\t\t\t\t\t\t\t\tdata-responsive=\"off\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-frames='[{\"from\":\"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;\",\"mask\":\"x:0px;y:0px;\",\"speed\":1500,\"to\":\"o:1;\",\"delay\":1000,\"ease\":\"Power3.easeInOut\"},{\"delay\":\"wait\",\"speed\":1000,\"to\":\"auto:auto;\",\"mask\":\"x:0;y:0;\",\"ease\":\"Power3.easeInOut\"},{\"frame\":\"hover\",\"speed\":\"300\",\"ease\":\"Power1.easeInOut\",\"to\":\"o:1;rX:0;rY:0;rZ:0;z:0;\",\"style\":\"c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:1px 1px 1px 1px;\"}]'\n");
      out.write("\t\t\t\t\t\t\t\tdata-textAlign=\"['center','center','center','center']\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingtop=\"[12,12,12,12]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingright=\"[30,35,35,15]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingbottom=\"[12,12,12,12]\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-paddingleft=\"[30,35,35,15]\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"\"></div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!-- SLIDE  -->\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div><!-- END REVOLUTION SLIDER -->  \n");
      out.write("\t\t\t</div>  \n");
      out.write("\t\t</div>  \n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("        <!-- Main Slider -->\n");
      out.write("\t\t<div class=\"content-block\">\n");
      out.write("            \n");
      out.write("\t\t\t<!-- Our Services -->\n");
      out.write("\t\t\t<div class=\"section-area content-inner service-info-bx\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-bx\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"action-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"assets/images/our-services/msbte.jpg\" alt=\"msbte\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"info-bx text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feature-box-sm radius bg-white\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bank text-primary\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4><a href=\"login?action=msbteLogin\">MSBTE Login</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"login?action=msbteLogin\" class=\"btn radius-xl\">Login</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-bx\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"action-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"assets/images/our-services/msbteinstitute.jpg\" alt=\"institute\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"info-bx text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feature-box-sm radius bg-white\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-book text-primary\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4><a href=\"login?action=instituteLogin\">Institute Login</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"login?action=instituteLogin\" class=\"btn radius-xl\">Login</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-4 col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"service-bx m-b0\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"action-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"assets/images/our-services/pic2.jpg\" alt=\"student\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"info-bx text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feature-box-sm radius bg-white\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-file-text-o text-primary\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4><a href=\"login?action=studentLogin\">Student Login</a></h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"login?action=studentLogin\" class=\"btn radius-xl\">Login</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("            <!-- Our Services END -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("<!-- Scripts Start-->\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- External JavaScripts -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/magnific-popup/magnific-popup.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/waypoints-min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/counterup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/imagesloaded/imagesloaded.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/masonry.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/filter.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"assets/js/contact.js\"></script>\r\n");
      out.write("<!-- Revolution JavaScripts Files -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.actions.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.kenburn.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.migration.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.navigation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.parallax.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.video.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("\tvar ttrevapi;\r\n");
      out.write("\tvar tpj =jQuery;\r\n");
      out.write("\tif(tpj(\"#rev_slider_486_1\").revolution == undefined){\r\n");
      out.write("\t\trevslider_showDoubleJqueryError(\"#rev_slider_486_1\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tttrevapi = tpj(\"#rev_slider_486_1\").show().revolution({\r\n");
      out.write("\t\t\tsliderType:\"standard\",\r\n");
      out.write("\t\t\tjsFileLocation:\"assets/vendors/revolution/js/\",\r\n");
      out.write("\t\t\tsliderLayout:\"fullwidth\",\r\n");
      out.write("\t\t\tdottedOverlay:\"none\",\r\n");
      out.write("\t\t\tdelay:9000,\r\n");
      out.write("\t\t\tnavigation: {\r\n");
      out.write("\t\t\t\tkeyboardNavigation:\"on\",\r\n");
      out.write("\t\t\t\tkeyboard_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\tmouseScrollNavigation:\"off\",\r\n");
      out.write("\t\t\t\tmouseScrollReverse:\"default\",\r\n");
      out.write("\t\t\t\tonHoverStop:\"on\",\r\n");
      out.write("\t\t\t\ttouch:{\r\n");
      out.write("\t\t\t\t\ttouchenabled:\"on\",\r\n");
      out.write("\t\t\t\t\tswipe_threshold: 75,\r\n");
      out.write("\t\t\t\t\tswipe_min_touches: 1,\r\n");
      out.write("\t\t\t\t\tswipe_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\t\tdrag_block_vertical: false\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t,\r\n");
      out.write("\t\t\t\tarrows: {\r\n");
      out.write("\t\t\t\t\tstyle: \"uranus\",\r\n");
      out.write("\t\t\t\t\tenable: true,\r\n");
      out.write("\t\t\t\t\thide_onmobile: false,\r\n");
      out.write("\t\t\t\t\thide_onleave: false,\r\n");
      out.write("\t\t\t\t\ttmp: '',\r\n");
      out.write("\t\t\t\t\tleft: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"left\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tright: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"right\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tviewPort: {\r\n");
      out.write("\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\toutof:\"pause\",\r\n");
      out.write("\t\t\t\tvisible_area:\"80%\",\r\n");
      out.write("\t\t\t\tpresize:false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tresponsiveLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tvisibilityLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridwidth:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridheight:[768,600,600,600],\r\n");
      out.write("\t\t\tlazyType:\"none\",\r\n");
      out.write("\t\t\tparallax: {\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t\torigo:\"enterpoint\",\r\n");
      out.write("\t\t\t\tspeed:400,\r\n");
      out.write("\t\t\t\tlevels:[5,10,15,20,25,30,35,40,45,50,46,47,48,49,50,55],\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshadow:0,\r\n");
      out.write("\t\t\tspinner:\"off\",\r\n");
      out.write("\t\t\tstopLoop:\"off\",\r\n");
      out.write("\t\t\tstopAfterLoops:-1,\r\n");
      out.write("\t\t\tstopAtSlide:-1,\r\n");
      out.write("\t\t\tshuffle:\"off\",\r\n");
      out.write("\t\t\tautoHeight:\"off\",\r\n");
      out.write("\t\t\thideThumbsOnMobile:\"off\",\r\n");
      out.write("\t\t\thideSliderAtLimit:0,\r\n");
      out.write("\t\t\thideCaptionAtLimit:0,\r\n");
      out.write("\t\t\thideAllCaptionAtLilmit:0,\r\n");
      out.write("\t\t\tdebugMode:false,\r\n");
      out.write("\t\t\tfallbacks: {\r\n");
      out.write("\t\t\t\tsimplifyAll:\"off\",\r\n");
      out.write("\t\t\t\tnextSlideOnWindowFocus:\"off\",\r\n");
      out.write("\t\t\t\tdisableFocusListener:false,\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("  <!-- Scripts End-->\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
