/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2024-04-13 14:18:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.epayment.Bean.InstituteBean;

public final class institute_005fProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/alljs.jsp", Long.valueOf(1711359392000L));
    _jspx_dependants.put("/allcss.jsp", Long.valueOf(1711359392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.epayment.Bean.InstituteBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- META ============================================= -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"\" />\r\n");
      out.write("\t<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DESCRIPTION -->\r\n");
      out.write("\t<meta name=\"description\" content=\"EduChamp : Education HTML Template\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- FAVICONS ICON ============================================= -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"assets/images/msbte logo.png\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/msbte logo.png\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- MOBILE SPECIFIC ============================================= -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- All PLUGINS CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/assets.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/calendar/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- TYPOGRAPHY ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/typography.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SHORTCODES ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/shortcodes/shortcodes.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- STYLESHEETS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/layers.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/settings.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/navigation.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/dashboard.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER END -->\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("<title>Institute Profile</title>\n");
      out.write("</head>\n");
      out.write("<body class=\"ttr-opened-sidebar ttr-pinned-sidebar\">\n");
      out.write("\t\n");
      out.write("\t\n");

InstituteBean editInstitute =(InstituteBean)request.getAttribute("ib");

      out.write("\n");
      out.write("\t\n");
      out.write("\t<!-- header start -->\n");
      out.write("\t<header class=\"ttr-header\">\n");
      out.write("\t\t<div class=\"ttr-header-wrapper\">\n");
      out.write("\t\t\t<!--sidebar menu toggler start -->\n");
      out.write("\t\t\t<div class=\"ttr-toggle-sidebar ttr-material-button\">\n");
      out.write("\t\t\t\t<i class=\"ti-close ttr-open-icon\"></i>\n");
      out.write("\t\t\t\t<i class=\"ti-menu ttr-close-icon\"></i>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--sidebar menu toggler end -->\n");
      out.write("\t\t\t<!--logo start -->\n");
      out.write("\t\t\t<div class=\"ttr-logo-box\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<a href=\"Home?action=Dashboard\" class=\"ttr-logo\">\n");
      out.write("\t\t\t\t\t\t<img class=\"ttr-logo-desktop\" alt=\"\" src=\"assets/images/msbte logo.png\" width=\"160\" height=\"27\">\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- header end -->\n");
      out.write("\t<!-- Left sidebar menu start -->\n");
      out.write("\t<div class=\"ttr-sidebar\">\n");
      out.write("\t\t<div class=\"ttr-sidebar-wrapper content-scroll\">\n");
      out.write("\t\t\t<!-- side menu logo start -->\n");
      out.write("\t\t\t<div class=\"ttr-sidebar-logo\">\n");
      out.write("\t\t\t\t<a href=\"#\"><img alt=\"\" src=\"assets/images/msbte logo.png\" width=\"122\" height=\"27\"></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- side menu logo end -->\n");
      out.write("\t\t\t<!-- sidebar menu start -->\n");
      out.write("\t\t\t<nav class=\"ttr-sidebar-navi\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"instituteOption.jsp\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-home\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Dashboard</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li>\n");
      out.write("\t\t\t\t\t\t<a href=\"Institute?action=InstituteProfile&institute_id=");
      out.print(session.getAttribute("institute_id")!=null?session.getAttribute("institute_id"):"");
      out.write("\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-book\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Institute Profile</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"Student?action=studList&institute_id=");
      out.print(session.getAttribute("institute_id")!=null?session.getAttribute("institute_id"):"");
      out.write("\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-user\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Manage Student</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li>\n");
      out.write("\t\t\t\t\t\t<a href=\"ExamForm?action=examList\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-bookmark-alt\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Exam Form Approval</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-layout-accordion-list\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Offline Payment List</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li>\n");
      out.write("\t\t\t\t\t\t<a href=\"ExamForm?action=seatNoListInstitute\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-bookmark-alt\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">SeatNo List</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li>\n");
      out.write("\t\t\t\t\t\t<a href=\"login?action=instituteLogout\" class=\"ttr-material-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"ttr-icon\"><i class=\"ti-arrow-left\"></i></span>\n");
      out.write("\t\t                \t<span class=\"ttr-label\">Log Out</span>\n");
      out.write("\t\t                </a>\n");
      out.write("\t\t            </li>\n");
      out.write("\t\t            <li class=\"ttr-seperate\"></li>\n");
      out.write("\t\t\t\t</ul>\t\n");
      out.write("\t\t\t\t<!-- sidebar menu end -->\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<!-- sidebar menu end -->\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Left sidebar menu end -->\n");
      out.write("\t<!--Main container start -->\n");
      out.write("\t<main class=\"ttr-wrapper\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"db-breadcrumb\">\n");
      out.write("\t\t\t\t<h4 class=\"breadcrumb-title\">User Profile</h4>\n");
      out.write("\t\t\t\t<ul class=\"db-breadcrumb-list\">\n");
      out.write("\t\t\t\t\t<li>Institute Registration</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<!-- Your Profile Views Chart -->\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 m-b30\">\n");
      out.write("\t\t\t\t\t<div class=\"widget-box\">\n");
      out.write("\t\t\t\t\t\t<div class=\"wc-title\">\n");
      out.write("\t\t\t\t\t\t\t<h4>Institute Registration</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-inner\">\n");
      out.write("\t\t\t\t\t\t\t<form class=\"edit-profile m-b30\"  method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t<fieldset disabled=\"disabled\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"institute_id\" name=\"institute_id\" type=\"hidden\"  class=\"form-control\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getInstitute_id():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-10  ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Institute Details</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Institute Name</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"institute_name\" name=\"institute_name\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getInstitute_name():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Institute Code</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"institute_code\" name=\"institute_code\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getInstitute_code():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Email</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"email\" name=\"email\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getEmail():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Mobile No.</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"mobile\" name=\"mobile\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getMobile():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Address</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"address\" name=\"address\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getAddress():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Registerd Date:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"registerd_date\" name=\"registerd_date\" class=\"form-control\" type=\"date\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getRegisterd_date():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Username</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"username\" name=\"username\" class=\"form-control\" type=\"text\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getUsername():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-2 col-form-label\">Password</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"password\" name=\"password\" class=\"form-control\" type=\"password\" value=\"");
      out.print((editInstitute!=null)?editInstitute.getPassword():"");
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- Your Profile Views Chart END-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</main>\n");
      out.write("\t<div class=\"ttr-overlay\"></div>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- External JavaScripts -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/magnific-popup/magnific-popup.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/waypoints-min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/counterup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/imagesloaded/imagesloaded.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/masonry.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/filter.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"assets/js/contact.js\"></script>\r\n");
      out.write("<!-- Revolution JavaScripts Files -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.actions.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.kenburn.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.migration.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.navigation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.parallax.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.video.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("\tvar ttrevapi;\r\n");
      out.write("\tvar tpj =jQuery;\r\n");
      out.write("\tif(tpj(\"#rev_slider_486_1\").revolution == undefined){\r\n");
      out.write("\t\trevslider_showDoubleJqueryError(\"#rev_slider_486_1\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tttrevapi = tpj(\"#rev_slider_486_1\").show().revolution({\r\n");
      out.write("\t\t\tsliderType:\"standard\",\r\n");
      out.write("\t\t\tjsFileLocation:\"assets/vendors/revolution/js/\",\r\n");
      out.write("\t\t\tsliderLayout:\"fullwidth\",\r\n");
      out.write("\t\t\tdottedOverlay:\"none\",\r\n");
      out.write("\t\t\tdelay:9000,\r\n");
      out.write("\t\t\tnavigation: {\r\n");
      out.write("\t\t\t\tkeyboardNavigation:\"on\",\r\n");
      out.write("\t\t\t\tkeyboard_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\tmouseScrollNavigation:\"off\",\r\n");
      out.write("\t\t\t\tmouseScrollReverse:\"default\",\r\n");
      out.write("\t\t\t\tonHoverStop:\"on\",\r\n");
      out.write("\t\t\t\ttouch:{\r\n");
      out.write("\t\t\t\t\ttouchenabled:\"on\",\r\n");
      out.write("\t\t\t\t\tswipe_threshold: 75,\r\n");
      out.write("\t\t\t\t\tswipe_min_touches: 1,\r\n");
      out.write("\t\t\t\t\tswipe_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\t\tdrag_block_vertical: false\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t,\r\n");
      out.write("\t\t\t\tarrows: {\r\n");
      out.write("\t\t\t\t\tstyle: \"uranus\",\r\n");
      out.write("\t\t\t\t\tenable: true,\r\n");
      out.write("\t\t\t\t\thide_onmobile: false,\r\n");
      out.write("\t\t\t\t\thide_onleave: false,\r\n");
      out.write("\t\t\t\t\ttmp: '',\r\n");
      out.write("\t\t\t\t\tleft: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"left\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tright: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"right\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tviewPort: {\r\n");
      out.write("\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\toutof:\"pause\",\r\n");
      out.write("\t\t\t\tvisible_area:\"80%\",\r\n");
      out.write("\t\t\t\tpresize:false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tresponsiveLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tvisibilityLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridwidth:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridheight:[768,600,600,600],\r\n");
      out.write("\t\t\tlazyType:\"none\",\r\n");
      out.write("\t\t\tparallax: {\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t\torigo:\"enterpoint\",\r\n");
      out.write("\t\t\t\tspeed:400,\r\n");
      out.write("\t\t\t\tlevels:[5,10,15,20,25,30,35,40,45,50,46,47,48,49,50,55],\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshadow:0,\r\n");
      out.write("\t\t\tspinner:\"off\",\r\n");
      out.write("\t\t\tstopLoop:\"off\",\r\n");
      out.write("\t\t\tstopAfterLoops:-1,\r\n");
      out.write("\t\t\tstopAtSlide:-1,\r\n");
      out.write("\t\t\tshuffle:\"off\",\r\n");
      out.write("\t\t\tautoHeight:\"off\",\r\n");
      out.write("\t\t\thideThumbsOnMobile:\"off\",\r\n");
      out.write("\t\t\thideSliderAtLimit:0,\r\n");
      out.write("\t\t\thideCaptionAtLimit:0,\r\n");
      out.write("\t\t\thideAllCaptionAtLilmit:0,\r\n");
      out.write("\t\t\tdebugMode:false,\r\n");
      out.write("\t\t\tfallbacks: {\r\n");
      out.write("\t\t\t\tsimplifyAll:\"off\",\r\n");
      out.write("\t\t\t\tnextSlideOnWindowFocus:\"off\",\r\n");
      out.write("\t\t\t\tdisableFocusListener:false,\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
