/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2024-04-14 18:20:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.JSONArray;
import org.json.JSONObject;
import com.epayment.Bean.ExamFormBean;
import com.epayment.Bean.InstituteBean;
import com.epayment.Bean.StudentBean;
import java.util.List;
import java.util.ArrayList;
import com.epayment.Bean.SubjectBean;

public final class printExamForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/alljs.jsp", Long.valueOf(1711359392000L));
    _jspx_dependants.put("/allcss.jsp", Long.valueOf(1713035840294L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1713035871727L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.epayment.Bean.StudentBean");
    _jspx_imports_classes.add("com.epayment.Bean.InstituteBean");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("com.epayment.Bean.ExamFormBean");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.epayment.Bean.SubjectBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
JSONObject jobj=(JSONObject)request.getAttribute("jobj");
      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- META ============================================= -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"\" />\r\n");
      out.write("\t<meta name=\"robots\" content=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- DESCRIPTION -->\r\n");
      out.write("\t<meta name=\"description\" content=\"EduChamp : Education HTML Template\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- FAVICONS ICON ============================================= -->\r\n");
      out.write("\t<link rel=\"icon\" href=\"assets/images/msbte logo.png\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/images/msbte logo.png\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- MOBILE SPECIFIC ============================================= -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- All PLUGINS CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/assets.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/calendar/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- TYPOGRAPHY ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/typography.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SHORTCODES ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/shortcodes/shortcodes.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- STYLESHEETS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER CSS ============================================= -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/layers.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/settings.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendors/revolution/css/navigation.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/dashboard.css\">\r\n");
      out.write("\t<link class=\"skin\" rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/color/color-1.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- REVOLUTION SLIDER END -->\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

 response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" <title>Exam Form </title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media print {\r\n");
      out.write("    #printButtonContainer {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("}</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ttr-opened-sidebar ttr-pinned-sidebar\">\r\n");
      out.write("    <!-- header start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"bg\">\r\n");

 response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

      out.write("\r\n");
      out.write("\t<!-- Header Top ==== -->\r\n");
      out.write("    <header class=\"header rs-nav\">\r\n");
      out.write("\t\t<div class=\"sticky-header navbar-expand-lg\">\r\n");
      out.write("             <a href=\"Home?action=Dashboard\"><img src=\"assets/images/MaharashtraSBTEHeader.jpg\" alt=\"logo\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("     <!-- Header Top END ==== -->  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <!-- header end -->\r\n");
      out.write("   <!--Main container start -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"col-lg-12 m-b30\">\r\n");
      out.write("\t\t\t<div class=\"widget-box\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"widget-inner\">\t\t\t     \r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\" style=\"color: black\">\r\n");
      out.write("                \r\n");
      out.write("                <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <h4 style=\"text-align: center;\">Maharashtra State Board of Technical Education, Mumbai.</h4>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h4 style=\"text-align: center;\">Exam Form</h4>\r\n");
      out.write("                 </td>\r\n");
      out.write("                 </table>\r\n");
      out.write("                 <table class=\"table table-bordered\" style=\"color: black\">\r\n");
      out.write("                   <hr style=\"border: 0.9px solid grey;\">\r\n");
      out.write("                <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>ENROLLMENT NUMBER :");
      out.print((jobj!=null)?jobj.get("enrollment_no"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>INSTITUTE CODE :");
      out.print((jobj!=null)?jobj.get("institute_code"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t         </tr>\r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>CANDIDATE NAME :");
      out.print((jobj!=null)?jobj.get("fullname"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Date of Bith:");
      out.print((jobj!=null)?jobj.get("dob"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("\t\t\t         <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Institute CODE & NAME :");
      out.print((jobj!=null)?jobj.get("institute_code"):"");
      out.write(' ');
      out.write('&');
      out.write(' ');
      out.print((jobj!=null)?jobj.get("institute_name"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>PROGRAM/COURSE NAME :");
      out.print((jobj!=null)?jobj.get("course_name"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>COURSE/YEAR-SCHEME :");
      out.print((jobj!=null)?jobj.get("semester"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t\t   <td>\r\n");
      out.write("\t\t\t\t\t\t<h5>PAYMENT MODE :");
      out.print((jobj!=null)?jobj.get("payment"):"");
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t\t   <td><img alt=\"\" src=\"fetchimage?type=UserPhoto&image=");
      out.print((jobj.get("stud_photo")!=null)?jobj.get("stud_photo"):"");
      out.write("\"> </td>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<h5>SUBJECT APPEARING FOR :\r\n");
      out.write("\t\t\t\t\t");

					if(jobj!=null)
					{int i=0;
					JSONArray jarray=new JSONArray(jobj.getString("details"));
					for(i=0;i<jarray.length();i++)
					{
						JSONObject job=jarray.getJSONObject(i);	
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print((job!=null)?job.get("subject"):"");
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t");
}}
      out.write("\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t   </tr>\r\n");
      out.write("              \r\n");
      out.write("\t\t\t   </table>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t     <table class=\"table table-bordered\" style=\"color: black\">\r\n");
      out.write("               <tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 style=\"text-align: left;\">Attested By<br><br>Principal/HOD:-<br><br>Sign and stamp\r\n");
      out.write("\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t   </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Date: <span id=\"currentDate\"></span></h5>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t   </table>\r\n");
      out.write("\t\t\t   <div id=\"printButtonContainer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary\" id=\"print\" onclick=\"window.print();\">Print</button>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- External JavaScripts -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/magnific-popup/magnific-popup.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/waypoints-min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/counter/counterup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/imagesloaded/imagesloaded.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/masonry.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/masonry/filter.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/owl-carousel/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("<script src=\"assets/js/contact.js\"></script>\r\n");
      out.write("<!-- Revolution JavaScripts Files -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.tools.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/jquery.themepunch.revolution.min.js\"></script>\r\n");
      out.write("<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.actions.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.kenburn.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.migration.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.navigation.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.parallax.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendors/revolution/js/extensions/revolution.extension.video.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("\tvar ttrevapi;\r\n");
      out.write("\tvar tpj =jQuery;\r\n");
      out.write("\tif(tpj(\"#rev_slider_486_1\").revolution == undefined){\r\n");
      out.write("\t\trevslider_showDoubleJqueryError(\"#rev_slider_486_1\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tttrevapi = tpj(\"#rev_slider_486_1\").show().revolution({\r\n");
      out.write("\t\t\tsliderType:\"standard\",\r\n");
      out.write("\t\t\tjsFileLocation:\"assets/vendors/revolution/js/\",\r\n");
      out.write("\t\t\tsliderLayout:\"fullwidth\",\r\n");
      out.write("\t\t\tdottedOverlay:\"none\",\r\n");
      out.write("\t\t\tdelay:9000,\r\n");
      out.write("\t\t\tnavigation: {\r\n");
      out.write("\t\t\t\tkeyboardNavigation:\"on\",\r\n");
      out.write("\t\t\t\tkeyboard_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\tmouseScrollNavigation:\"off\",\r\n");
      out.write("\t\t\t\tmouseScrollReverse:\"default\",\r\n");
      out.write("\t\t\t\tonHoverStop:\"on\",\r\n");
      out.write("\t\t\t\ttouch:{\r\n");
      out.write("\t\t\t\t\ttouchenabled:\"on\",\r\n");
      out.write("\t\t\t\t\tswipe_threshold: 75,\r\n");
      out.write("\t\t\t\t\tswipe_min_touches: 1,\r\n");
      out.write("\t\t\t\t\tswipe_direction: \"horizontal\",\r\n");
      out.write("\t\t\t\t\tdrag_block_vertical: false\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t,\r\n");
      out.write("\t\t\t\tarrows: {\r\n");
      out.write("\t\t\t\t\tstyle: \"uranus\",\r\n");
      out.write("\t\t\t\t\tenable: true,\r\n");
      out.write("\t\t\t\t\thide_onmobile: false,\r\n");
      out.write("\t\t\t\t\thide_onleave: false,\r\n");
      out.write("\t\t\t\t\ttmp: '',\r\n");
      out.write("\t\t\t\t\tleft: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"left\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tright: {\r\n");
      out.write("\t\t\t\t\t\th_align: \"right\",\r\n");
      out.write("\t\t\t\t\t\tv_align: \"center\",\r\n");
      out.write("\t\t\t\t\t\th_offset: 10,\r\n");
      out.write("\t\t\t\t\t\tv_offset: 0\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tviewPort: {\r\n");
      out.write("\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\toutof:\"pause\",\r\n");
      out.write("\t\t\t\tvisible_area:\"80%\",\r\n");
      out.write("\t\t\t\tpresize:false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tresponsiveLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tvisibilityLevels:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridwidth:[1240,1024,778,480],\r\n");
      out.write("\t\t\tgridheight:[768,600,600,600],\r\n");
      out.write("\t\t\tlazyType:\"none\",\r\n");
      out.write("\t\t\tparallax: {\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t\torigo:\"enterpoint\",\r\n");
      out.write("\t\t\t\tspeed:400,\r\n");
      out.write("\t\t\t\tlevels:[5,10,15,20,25,30,35,40,45,50,46,47,48,49,50,55],\r\n");
      out.write("\t\t\t\ttype:\"scroll\",\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshadow:0,\r\n");
      out.write("\t\t\tspinner:\"off\",\r\n");
      out.write("\t\t\tstopLoop:\"off\",\r\n");
      out.write("\t\t\tstopAfterLoops:-1,\r\n");
      out.write("\t\t\tstopAtSlide:-1,\r\n");
      out.write("\t\t\tshuffle:\"off\",\r\n");
      out.write("\t\t\tautoHeight:\"off\",\r\n");
      out.write("\t\t\thideThumbsOnMobile:\"off\",\r\n");
      out.write("\t\t\thideSliderAtLimit:0,\r\n");
      out.write("\t\t\thideCaptionAtLimit:0,\r\n");
      out.write("\t\t\thideAllCaptionAtLilmit:0,\r\n");
      out.write("\t\t\tdebugMode:false,\r\n");
      out.write("\t\t\tfallbacks: {\r\n");
      out.write("\t\t\t\tsimplifyAll:\"off\",\r\n");
      out.write("\t\t\t\tnextSlideOnWindowFocus:\"off\",\r\n");
      out.write("\t\t\t\tdisableFocusListener:false,\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("        // Get current date\r\n");
      out.write("        var currentDate = new Date();\r\n");
      out.write("\r\n");
      out.write("        // Format date as YYYY-MM-DD\r\n");
      out.write("        var formattedDate = currentDate.getDate() + '-' + (currentDate.getMonth() + 1) + '-' + currentDate.getFullYear();\r\n");
      out.write("\r\n");
      out.write("        // Display formatted date\r\n");
      out.write("        document.getElementById('currentDate').innerHTML = formattedDate;\r\n");
      out.write("    </script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("     function getSubjectDetails() {\t\r\n");
      out.write("     var course_name=document.getElementById(\"course_name\").value;\r\n");
      out.write("     var semester=document.getElementById(\"semester\").value;\r\n");
      out.write("     $(\"#subject tr\").remove();\r\n");
      out.write("     if(course_name!=='' && semester!==''){\r\n");
      out.write("\t       $.ajax({\r\n");
      out.write("\t          url:\"ExamForm?action=getFormDetails&course_name=\"+course_name+\"&semester=\"+semester,\r\n");
      out.write("\t       \t   success:function(result){\r\n");
      out.write("\t       \t\t$.each(result, function(i, subject) {\r\n");
      out.write("\t       \t\t var sub_choice= result[i].checkbox;\r\n");
      out.write("       \t\t\t $('<tr>').html(\"<td style=font-size:15px;>\" + result[i].subject + \"</td> <td><input type='checkbox' value='TH'></td> <td><input type='checkbox' value='TW'></td> <td><input type='checkbox' value='PR'></td> <td><input type='checkbox' value='OR'></td> <td><input type='checkbox' value='SW'></td> <td><input type='checkbox' value='TM'></td> <td><input type='checkbox' value='PM'></td>\").appendTo('#subject');\r\n");
      out.write("\t       \t\t});\r\n");
      out.write("\t       \t   } \r\n");
      out.write("\t          });\r\n");
      out.write("           }\r\n");
      out.write("           \r\n");
      out.write("\t   } \r\n");
      out.write(" </script> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
